theme: minima

title: "Liam Nomad"
description: "Data Engineer | Building scalable data pipelines | Open to opportunities"
email: "liam.nomad34@gmail.com"
linkedin: "https://www.linkedin.com/in/liam-nomad"
github: "https://github.com/LiamNomad"
